// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: hello.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Greeter_UnaryHello_FullMethodName        = "/helloworld.Greeter/UnaryHello"
	Greeter_HelloServerStream_FullMethodName = "/helloworld.Greeter/HelloServerStream"
	Greeter_HelloClientStream_FullMethodName = "/helloworld.Greeter/HelloClientStream"
	Greeter_HelloBiStreams_FullMethodName    = "/helloworld.Greeter/HelloBiStreams"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Unary
	UnaryHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// ServerStream
	HelloServerStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_HelloServerStreamClient, error)
	// ClientStream
	HelloClientStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_HelloClientStreamClient, error)
	// BiStreams
	HelloBiStreams(ctx context.Context, opts ...grpc.CallOption) (Greeter_HelloBiStreamsClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) UnaryHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_UnaryHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) HelloServerStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_HelloServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], Greeter_HelloServerStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterHelloServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_HelloServerStreamClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterHelloServerStreamClient struct {
	grpc.ClientStream
}

func (x *greeterHelloServerStreamClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) HelloClientStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_HelloClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], Greeter_HelloClientStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterHelloClientStreamClient{stream}
	return x, nil
}

type Greeter_HelloClientStreamClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterHelloClientStreamClient struct {
	grpc.ClientStream
}

func (x *greeterHelloClientStreamClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterHelloClientStreamClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) HelloBiStreams(ctx context.Context, opts ...grpc.CallOption) (Greeter_HelloBiStreamsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], Greeter_HelloBiStreams_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterHelloBiStreamsClient{stream}
	return x, nil
}

type Greeter_HelloBiStreamsClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterHelloBiStreamsClient struct {
	grpc.ClientStream
}

func (x *greeterHelloBiStreamsClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterHelloBiStreamsClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Unary
	UnaryHello(context.Context, *HelloRequest) (*HelloReply, error)
	// ServerStream
	HelloServerStream(*HelloRequest, Greeter_HelloServerStreamServer) error
	// ClientStream
	HelloClientStream(Greeter_HelloClientStreamServer) error
	// BiStreams
	HelloBiStreams(Greeter_HelloBiStreamsServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) UnaryHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryHello not implemented")
}
func (UnimplementedGreeterServer) HelloServerStream(*HelloRequest, Greeter_HelloServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloServerStream not implemented")
}
func (UnimplementedGreeterServer) HelloClientStream(Greeter_HelloClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloClientStream not implemented")
}
func (UnimplementedGreeterServer) HelloBiStreams(Greeter_HelloBiStreamsServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloBiStreams not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_UnaryHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).UnaryHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_UnaryHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).UnaryHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_HelloServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).HelloServerStream(m, &greeterHelloServerStreamServer{stream})
}

type Greeter_HelloServerStreamServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterHelloServerStreamServer struct {
	grpc.ServerStream
}

func (x *greeterHelloServerStreamServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_HelloClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).HelloClientStream(&greeterHelloClientStreamServer{stream})
}

type Greeter_HelloClientStreamServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterHelloClientStreamServer struct {
	grpc.ServerStream
}

func (x *greeterHelloClientStreamServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterHelloClientStreamServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_HelloBiStreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).HelloBiStreams(&greeterHelloBiStreamsServer{stream})
}

type Greeter_HelloBiStreamsServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterHelloBiStreamsServer struct {
	grpc.ServerStream
}

func (x *greeterHelloBiStreamsServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterHelloBiStreamsServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryHello",
			Handler:    _Greeter_UnaryHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloServerStream",
			Handler:       _Greeter_HelloServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HelloClientStream",
			Handler:       _Greeter_HelloClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HelloBiStreams",
			Handler:       _Greeter_HelloBiStreams_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
